export const EXAMPLES: Record<string, string> = {
  valid1: `MISION "vuelo_simple"\n  DESPEGAR ALTITUD 50 m\n  ATERRIZAR\nFIN`,
  valid2: `MISION "inspeccion_perimetral"\n  DESPEGAR ALTITUD 30 m\n  SENSOR bateria FRECUENCIA 2 s\n\n  # Primer tramo: subir a altura de crucero y avanzar hacia el punto A\n  MOVER arriba 10 m\n  MOVER norte 25 m VELOCIDAD 6\n  MOVER noreste 15 m VELOCIDAD 6\n  SENSOR temperatura FRECUENCIA 5 s\n\n  SI temperatura > 35 ENTONCES\n    SI bateria < 15 ENTONCES\n      ATERRIZAR\n    FIN\n  FIN\n\n  # Segundo tramo: recorrido en L hacia el punto B\n  MOVER este 20 m VELOCIDAD 4\n  MOVER sureste 10 m\n  MOVER sur 15 m VELOCIDAD 3\n  SENSOR viento FRECUENCIA 3 s\n\n  SI viento > 40 ENTONCES\n    MOVER abajo 10 m\n  FIN\n\n  # Tercer tramo: descenso y regreso\n  MOVER abajo 5 m\n  MOVER suroeste 20 m VELOCIDAD 5\n  MOVER oeste 15 m\n  SENSOR bateria FRECUENCIA 1 s\n\n  SI bateria < 25 ENTONCES\n    MOVER BASE\n  FIN\n\n  MOVER BASE\n  ATERRIZAR\nFIN`,
  valid3: `MISION "reconocimiento"\n  DESPEGAR ALTITUD 80 m\n  MOVER norte 150 m\n  MOVER este 100 m\n  SENSOR viento FRECUENCIA 5 s\n  SI viento > 30 ENTONCES\n    ATERRIZAR\n  FIN\n  MOVER BASE\n  ATERRIZAR\nFIN`,
  messi: `MISION "escribir_messi"\n  DESPEGAR ALTITUD 10 m\n\n  # Bajar al nivel del subrayado e ir a la derecha (offset inicial de X)\n  MOVER sur 10 m\n  MOVER este 30 m\n  MOVER norte 10 m\n\n  # --- Letra M ---\n  MOVER norte 40 m\n  MOVER sureste 28 m\n  MOVER noreste 28 m\n  MOVER sur 40 m\n\n  # Separación para E: bajar 10m, avanzar 20m, subir 10m (forma el subrayado inferior)\n  MOVER sur 10 m\n  MOVER este 20 m\n  MOVER norte 10 m\n\n  # --- Letra E ---\n  MOVER norte 40 m\n  MOVER este 20 m\n  MOVER oeste 20 m\n  MOVER sur 20 m\n  MOVER este 20 m\n  MOVER oeste 20 m\n  MOVER sur 20 m\n  MOVER este 20 m\n  # Volver al punto inicial (bottom-left) para bajar por el mismo lugar y no duplicar líneas de subida/bajada\n  MOVER oeste 20 m\n\n  # Separación para S (ancho de letra 20 + separación 20 = 40): bajar 10m, avanzar 40m, subir 10m\n  MOVER sur 10 m\n  MOVER este 40 m\n  MOVER norte 10 m\n\n  # --- Letra S ---\n  MOVER este 20 m\n  MOVER norte 20 m\n  MOVER oeste 20 m\n  MOVER norte 20 m\n  MOVER este 20 m\n  # Volver por el mismo camino para no cruzar la letra\n  MOVER oeste 20 m\n  MOVER sur 20 m\n  MOVER este 20 m\n  MOVER sur 20 m\n  MOVER oeste 20 m\n\n  # Separación para segunda S: bajar 10m, avanzar 40m, subir 10m\n  MOVER sur 10 m\n  MOVER este 40 m\n  MOVER norte 10 m\n\n  # --- Segunda Letra S ---\n  MOVER este 20 m\n  MOVER norte 20 m\n  MOVER oeste 20 m\n  MOVER norte 20 m\n  MOVER este 20 m\n  # Volver por el mismo camino para no cruzar la letra\n  MOVER oeste 20 m\n  MOVER sur 20 m\n  MOVER este 20 m\n  MOVER sur 20 m\n  MOVER oeste 20 m\n\n  # Separación para I: bajar 10m, avanzar 40m, subir 10m\n  MOVER sur 10 m\n  MOVER este 40 m\n  MOVER norte 10 m\n\n  # --- Letra I ---\n  MOVER norte 40 m\n  MOVER sur 40 m\n\n  # Volver a la base por la misma línea inferior del subrayado (Y = 10)\n  MOVER sur 10 m\n  MOVER oeste 210 m\n  MOVER norte 10 m\n  MOVER BASE\n  ATERRIZAR\nFIN`,
  invalid1: `MISION "error_sin_numero"\n  DESPEGAR ALTITUD\nFIN`,
  invalid2: `MISION "error_falta_fin"\n  DESPEGAR ALTITUD 30 m\n  ATERRIZAR`,
  invalid3: `MISION "error_cmd_invalido"\n  DESPEGAR ALTITUD 80 m\n  GIRAR izquierda 90\nFIN`,
};

export const EXAMPLE = EXAMPLES.valid2;
